name: Update Repository

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          
      - name: Set up dependencies
        run: |
           sudo apt update
           sudo apt install -y wireguard
           sudo ACCEPT_EULA=Y apt-get install msodbcsql18 -y
           sudo pip install pyodbc 

      - name: Write file
        env: 
           WG_CONFIG: ${{ secrets.WG_CONFIG }}
        run: |
           sudo bash -c 'echo "$WG_CONFIG" > /etc/wireguard/wg0.conf'
           sudo sed -n '6p' /etc/wireguard/wg0.conf

      - name: Start wireguard    
        run: |
           sudo wg-quick up wg0
           sleep 1
           sudo wg

