name: Update Repository

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
        
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          
      - name: Set up dependencies
        run: |
           sudo apt-get remove --purge man-db
           sudo apt install -y wireguard
           sudo ACCEPT_EULA=Y apt-get install msodbcsql18 -y

      - name: Write file
        env: 
           WG_CONFIG: ${{ secrets.WG_CONFIG }}
        run: |
           sudo -E bash -c 'echo "$WG_CONFIG" | base64 --decode > /etc/wireguard/wg0.conf'
           echo 'Verifying WG config...'
           sudo bash -c 'cat /etc/wireguard/wg0.conf | wc -l'           

      - name: Start wireguard    
        env:
           DB_ENDPOINT_VPN: ${{ secrets.DB_ENDPOINT_VPN }}
        run: |
           sudo wg-quick up wg0
           
      - name: Run Script
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
          DB_QUERY: ${{ secrets.DB_QUERY }}
        run: |
          cd $GITHUB_WORKSPACE/scripts
          pip install --user pyodbc 
          python -u main.py
          mv $GITHUB_WORKSPACE/scripts/index.html $GITHUB_WORKSPACE/index.html

      - name: Commit Changes
        run: |
          git config --global user.name "tmkhiem"
          git config --global user.email "tmkhiem@users.noreply.github.com"
          git add .
          git commit -m "Autoupdate repository"
          git push
