name: Update Repository

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          
      - name: Set up dependencies
        run: |
           sudo apt install -y wireguard
           sudo ACCEPT_EULA=Y apt-get install msodbcsql18 -y

      - name: Write file
        env: 
           WG_CONFIG: ${{ secrets.WG_CONFIG }}
        run: |
           sudo bash -c 'echo "$WG_CONFIG" > /etc/wireguard/wg0.conf'
           sudo sed -n '6p' /etc/wireguard/wg0.conf           

      - name: Start wireguard    
        env:
           DB_ENDPOINT_VPN: ${{ secrets.DB_ENDPOINT_VPN }}
        run: |
           sudo wg-quick up wg0
           sudo wg
           ping -c 10 $DB_ENDPOINT_VPN
           
           
      - name: Run Script
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
          DB_QUERY: ${{ secrets.DB_QUERY }}
        run: |
          cd $GITHUB_WORKSPACE/scripts
          pip install --user pyodbc 
          python -u main.py 

      - name: Test file
        run: |
          echo $GITHUB_WORKSPACE/scripts/index.html
