name: Update Repository

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Set up wireguard
        run: |
           sudo apt update
           sudo apt install -y wireguard

      - name: Write file
        env: 
          WG_CONFIG : ${{ secrets.WG_CONFIG }}
        run: |
           sudo echo "$WG_CONFIG" > /etc/wireguard/wg0.conf
           sudo sed -n '6p' /etc/wireguard/wg0.conf.conf
